// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the mobile number of the currently signed-in Mera Rashan user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const email = ctx.getUserEmail() ?? "";
    const mobile = email.split("@")[0] ?? "";
    return {
      content: [{ type: "text", text: `Signed in as mobile ${mobile}` }],
      structuredContent: { mobile }
    };
  }
});

// src/lib/mcp/tools/list-cards.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/upstream.ts
var BASE_URL = "https://data.merarashan.pk";
var FORWARD_PARAMS = ["month", "year", "monthYear", "rcNum", "status", "customerNumber"];
function requireMobile(ctx) {
  if (!ctx.isAuthenticated()) return { error: "Not authenticated." };
  const email = ctx.getUserEmail() ?? "";
  const mobile = email.split("@")[0] ?? "";
  if (!/^\d{6,15}$/.test(mobile)) return { error: "Signed-in user has no valid mobile identity." };
  return mobile;
}
async function fetchResource(resource, mobile, params) {
  const token = process.env.MERARASHAN_API_TOKEN;
  if (!token) throw new Error("MERARASHAN_API_TOKEN is not configured.");
  const url = new URL(`${BASE_URL}/${resource}`);
  url.searchParams.set("mobile", mobile);
  if (params) {
    for (const key of FORWARD_PARAMS) {
      const v = params[key];
      if (v) url.searchParams.set(key, v);
    }
  }
  const res = await fetch(url.toString(), {
    headers: { "x-api-key": token, Accept: "application/json" }
  });
  const text = await res.text();
  if (!res.ok) {
    throw new Error(`Upstream ${resource} failed [${res.status}]: ${text.slice(0, 500)}`);
  }
  try {
    return JSON.parse(text);
  } catch {
    return text;
  }
}

// src/lib/mcp/tools/list-cards.ts
var list_cards_default = defineTool2({
  name: "list_cards",
  title: "List rashan cards",
  description: "List all rashan cards belonging to the signed-in Mera Rashan user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (_input, ctx) => {
    const mobile = requireMobile(ctx);
    if (typeof mobile !== "string") {
      return { content: [{ type: "text", text: mobile.error }], isError: true };
    }
    try {
      const data = await fetchResource("cards", mobile);
      return {
        content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
        structuredContent: { cards: data }
      };
    } catch (err) {
      return { content: [{ type: "text", text: err.message }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
var list_transactions_default = defineTool3({
  name: "list_transactions",
  title: "List transactions",
  description: "List rashan transactions for the signed-in user. Optionally filter by month (1-12), year (YYYY), rashan card number, or customer number.",
  inputSchema: {
    month: z.string().regex(/^\d{1,2}$/).optional().describe("Month as 1-12."),
    year: z.string().regex(/^\d{4}$/).optional().describe("Year as YYYY."),
    rcNum: z.string().optional().describe("Rashan card number to scope the results."),
    customerNumber: z.string().optional().describe("Customer number to scope the results.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (input, ctx) => {
    const mobile = requireMobile(ctx);
    if (typeof mobile !== "string") {
      return { content: [{ type: "text", text: mobile.error }], isError: true };
    }
    try {
      const data = await fetchResource("transactions", mobile, input);
      return {
        content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
        structuredContent: { transactions: data }
      };
    } catch (err) {
      return { content: [{ type: "text", text: err.message }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-statements.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_statements_default = defineTool4({
  name: "list_statements",
  title: "List statements",
  description: "List rashan statements for the signed-in user. Optionally filter by month (1-12) and year (YYYY), or by a specific rashan card number.",
  inputSchema: {
    month: z2.string().regex(/^\d{1,2}$/).optional().describe("Month as 1-12."),
    year: z2.string().regex(/^\d{4}$/).optional().describe("Year as YYYY."),
    rcNum: z2.string().optional().describe("Rashan card number to scope the results.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (input, ctx) => {
    const mobile = requireMobile(ctx);
    if (typeof mobile !== "string") {
      return { content: [{ type: "text", text: mobile.error }], isError: true };
    }
    try {
      const data = await fetchResource("statements", mobile, input);
      return {
        content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
        structuredContent: { statements: data }
      };
    } catch (err) {
      return { content: [{ type: "text", text: err.message }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-customers.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_customers_default = defineTool5({
  name: "list_customers",
  title: "List customer profiles",
  description: "List the customer profiles (rashan account holders) linked to the signed-in Mera Rashan user's mobile number.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (_input, ctx) => {
    const mobile = requireMobile(ctx);
    if (typeof mobile !== "string") {
      return { content: [{ type: "text", text: mobile.error }], isError: true };
    }
    try {
      const data = await fetchResource("customers", mobile);
      return {
        content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
        structuredContent: { customers: data }
      };
    } catch (err) {
      return { content: [{ type: "text", text: err.message }], isError: true };
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "qbukjjextezbughdbsjo";
var mcp_default = defineMcp({
  name: "mera-rashan-mcp",
  title: "Mera Rashan",
  version: "0.1.0",
  instructions: "Tools for the signed-in Mera Rashan user. Use `whoami` to confirm identity, `list_customers` to see linked customer profiles, `list_cards` for rashan cards, `list_transactions` for transactions (optionally by month/year), and `list_statements` for monthly statements. All tools act only on the signed-in user's own data.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_customers_default, list_cards_default, list_transactions_default, list_statements_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
